-- AlterEnum
ALTER TYPE "ReactionType" ADD VALUE 'AGREE';
ALTER TYPE "ReactionType" ADD VALUE 'BUG';
ALTER TYPE "ReactionType" ADD VALUE 'FISH';
ALTER TYPE "ReactionType" ADD VALUE 'HYPE';
ALTER TYPE "ReactionType" ADD VALUE 'COIN';
ALTER TYPE "ReactionType" ADD VALUE 'THINK';
ALTER TYPE "ReactionType" ADD VALUE 'DIAMOND';
ALTER TYPE "ReactionType" ADD VALUE 'USEFUL';
ALTER TYPE "ReactionType" ADD VALUE 'CREATIVE';
