# HellcoreSync Configuration (Railway Edition)
mysql.host=roundhouse.proxy.rlwy.net
mysql.port=22206
mysql.database=railway
mysql.user=root
mysql.password=EtBwQFBpBCyWElJkxcCbTLFPGuNZxbHC
discord.webhook=https://discord.com/api/webhooks/1495099642671792261/LA6pwnEjA74swShTjPwX5qT5iBh_xHUBh6elQS8RK_OZF7anxO5hsXoIlBUsPSRvPavj
